spring:
  datasource:
    url: jdbc:mysql://localhost:3306/walkbookstore?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database:0
    host:172.0.0.1
    prot:6379
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
mybatis:
  mapper-locations: classpath*:mapper/*.xml
